version: '3.8'

services:
  # PHP 5.6 Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mesuk-meter-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=meesuk_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mesuk-meter-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: meesuk_db
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mesuk-meter-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db

volumes:
  mysql_data:
